## Stock (object)
+ id:5740db95f82359550284846d (required, string) - Unique Stock identifier.
+ productId:0001 (required, string) - The Product id.
+ warehouseId:001 (required, string) - The Warehouse id.
+ quantityInStock:100 (required, number) - The quantity in stock for this Product/Warehouse.
+ quantityReserved:0 (required, number) - The quantity reserved of this Product/Warehouse.

## Reserve (object)
+ id:HJeJVjeX (required, string) - Unique Reserve identifier.
+ warehouseId:001 (required, string) - The Warehouse id where the reserve was made.
+ quantity:1 (required, number) - The quantity reserved.
+ expirationTime: `2016-06-01T19:31:17.674Z` (required, string) - The Reserve expiration date/time (ISO8601 format).

## CreateStockRequest (object)
+ productId:0001 (required, string) - The Product id to set the stock.
+ warehouseId:001 (required, string) - The Warehouse id to set the stock.
+ quantityInStock:100 (required, number) - The quantity in stock for this Product/Warehouse.
+ quantityReserved:0 (optional, number) - The quantity reserved of this Product/Warehouse.

## UpdateStockRequest (object)
+ quantityInStock:100 (required, number) - The quantity in stock for this Product/Warehouse.
+ quantityReserved:0 (optional, number) - The quantity reserved of this Product/Warehouse.

## ReserveRequest (object)
+ productId:001 (required, string) - The Product id to reserve the stock.
+ warehouseId:0001 (required, string) - The Warehouse id to reserve the stock.
+ quantity:1 (required, number) - The quantity of this Product to reserve in this Warehouse.
+ reserveStockForMinutes:1440 (optional, number) - The minutes to reserve the stock until it expires.

## UnreserveRequest (object)
+ quantity:1 (required, number) - The quantity to unreserve.
