FORMAT: 1A
HOST: http://localhost:3000

# Stock ecomm service
Ecommerce Stock service using microbase framework (beta).

## MicroBase
MicroBase is a small framework to define and call services, and gives some basic utilities like config, logging, jobs and MongoDB access.
More info abot the framework [here](https://github.com/ncornag/microbase/tree/develop).

# Data Structures
<!-- include(dataStructures.apib) -->
# Group Stock
<!-- include(operations.apib) -->
