FORMAT: 1A
HOST: http://localhost:3000

# Stock ecomm service
Ecommerce Stock service using micro-base framework (beta).

## Micro-base
Micro-base is a small framework to define and call services, and gives some basic utilities like config, logging, jobs and MongoDB access.
More info abot the framework [here](https://github.com/ncornag/micro-base/tree/develop).

# Data Structures
<!-- include(dataStructures.apib) -->
# Group Stock
<!-- include(operations.apib) -->
