sudo: required
language: node_js
node_js:
  - '6'
branches:
  only:
  - master
  - develop
services:
  - mongodb
  - docker
cache:
  directories:
  - $HOME/.yarn-cache
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
env:
  global:
    - ISDEPLOY=$(echo ${TRAVIS_BRANCH} | grep -q "^.*/.*$" && echo true || echo false)
    - DEPLOY_NAME=$(echo ${TRAVIS_BRANCH} | sed s/deploy\\///)
install:
  - cd src
  - yarn --pure-lockfile
before_script:
  - sleep 15
script:
  - npm run test-cov-lcov
after_success:
  - cat ./lcov.info | ./node_modules/.bin/coveralls
  - cd ..
  - docker build -t $TRAVIS_REPO_SLUG:build .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker tag $TRAVIS_REPO_SLUG:build $TRAVIS_REPO_SLUG:develop;
    docker push $TRAVIS_REPO_SLUG:develop;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ -n "${TRAVIS_TAG}" ]; then
    docker tag $TRAVIS_REPO_SLUG:build $TRAVIS_REPO_SLUG:$TRAVIS_TAG;
    docker push $TRAVIS_REPO_SLUG:$TRAVIS_TAG;
    docker tag $TRAVIS_REPO_SLUG:build $TRAVIS_REPO_SLUG:latest;
    docker push $TRAVIS_REPO_SLUG:latest;
    fi
  - if [ "$ISDEPLOY" == "true" ]; then
    docker tag $TRAVIS_REPO_SLUG:build $TRAVIS_REPO_SLUG:$DEPLOY_NAME;
    docker push $TRAVIS_REPO_SLUG:$DEPLOY_NAME;
    fi
notifications:
  slack:
    secure: aPyoXSu6VN634erAwxxtf2dSoOhH1PbZOIlADNjDXyCL3nairpxYzPt2p3cQg/lUVjDnAIZPVX4M+x9StVrFq9fCw4SwNRjJy0AhUr+YINHM87EQiC0hjb4dLXXiSupNSYgX2o2dqlgb34OXRsC7NDxITzDCG521SoHcMrSnjFlkzbJPn89t/fWvpHmeoaRsxZ3vql+RaPp5omzoD79XYVqF33jkxvIjYkHkpPsw7zNmbVnS71K8nX+a5vkh+ztFJS/tkgsTtuhCj8at6Wl0xbQuPEqQr09LU5Yf5cC8nMt949Z7BxM2jD9IQ39IwRznLOVHtGK6o9/AAiW3MGHVGo0L3oZScwMneylNRnpWda7dr8tyJMQc05xe1PuHw4ck+RoP6G47M8jxgOjaqNal7+esQzNpojkIkEUkRrw+4lW3NQ40LyNu7lVhSKaml28MGY/PgY3r1UPlBL1BuX5Gzq88as8x+uZMxDmJ2ABlme1dAVPjABCcS1L+GklwS6ErbUnwJB9GzEgcmx5HlBM922FHhGOhncL85uqj4Brr4mPtQ3awlYmTSXLUXOOaLQALk4mp4icsyvtWiEzRmMTfnM1nq7L1nY0r46VQbSU+h3CaZq9gw0YDua4JVlTd+IEIXHO7Qh2KAVb5dUaFRKC38plwGk+C4gE5jJdKmh4a1/k=
